/*
* generated by Xtext
*/
package itu.dk.aamj.intentdsl.ui.outline;

import org.eclipse.xtext.ui.editor.outline.impl.DefaultOutlineTreeProvider;

/**
 * customization of the default outline structure
 * 
 */
public class IntentDslOutlineTreeProvider extends DefaultOutlineTreeProvider {
	
}
