/*
* generated by Xtext
*/

package itu.dk.aamj.intentdsl.services;

import com.google.inject.Singleton;
import com.google.inject.Inject;

import java.util.List;

import org.eclipse.xtext.*;
import org.eclipse.xtext.service.GrammarProvider;
import org.eclipse.xtext.service.AbstractElementFinder.*;

import org.eclipse.xtext.common.services.TerminalsGrammarAccess;

@Singleton
public class IntentDslGrammarAccess extends AbstractGrammarElementFinder {
	
	
	public class IntentElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Intent");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cIntentAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cIntentKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameEStringParserRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cTypeKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cTypeAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final RuleCall cTypeEStringParserRuleCall_4_1_0 = (RuleCall)cTypeAssignment_4_1.eContents().get(0);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cDataKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Assignment cDataAssignment_5_1 = (Assignment)cGroup_5.eContents().get(1);
		private final RuleCall cDataEStringParserRuleCall_5_1_0 = (RuleCall)cDataAssignment_5_1.eContents().get(0);
		private final Group cGroup_6 = (Group)cGroup.eContents().get(6);
		private final Keyword cExceptionNameKeyword_6_0 = (Keyword)cGroup_6.eContents().get(0);
		private final Assignment cExceptionNameAssignment_6_1 = (Assignment)cGroup_6.eContents().get(1);
		private final RuleCall cExceptionNameEStringParserRuleCall_6_1_0 = (RuleCall)cExceptionNameAssignment_6_1.eContents().get(0);
		private final Group cGroup_7 = (Group)cGroup.eContents().get(7);
		private final Keyword cExtrasKeyword_7_0 = (Keyword)cGroup_7.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_7_1 = (Keyword)cGroup_7.eContents().get(1);
		private final Assignment cExtrasAssignment_7_2 = (Assignment)cGroup_7.eContents().get(2);
		private final RuleCall cExtrasBundleParserRuleCall_7_2_0 = (RuleCall)cExtrasAssignment_7_2.eContents().get(0);
		private final Group cGroup_7_3 = (Group)cGroup_7.eContents().get(3);
		private final Keyword cCommaKeyword_7_3_0 = (Keyword)cGroup_7_3.eContents().get(0);
		private final Assignment cExtrasAssignment_7_3_1 = (Assignment)cGroup_7_3.eContents().get(1);
		private final RuleCall cExtrasBundleParserRuleCall_7_3_1_0 = (RuleCall)cExtrasAssignment_7_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_7_4 = (Keyword)cGroup_7.eContents().get(4);
		private final Group cGroup_8 = (Group)cGroup.eContents().get(8);
		private final Keyword cSucessCallbackKeyword_8_0 = (Keyword)cGroup_8.eContents().get(0);
		private final Assignment cSucessCallbackAssignment_8_1 = (Assignment)cGroup_8.eContents().get(1);
		private final RuleCall cSucessCallbackCallbackParserRuleCall_8_1_0 = (RuleCall)cSucessCallbackAssignment_8_1.eContents().get(0);
		private final Group cGroup_9 = (Group)cGroup.eContents().get(9);
		private final Keyword cPermissionsKeyword_9_0 = (Keyword)cGroup_9.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_9_1 = (Keyword)cGroup_9.eContents().get(1);
		private final Assignment cPermissionsAssignment_9_2 = (Assignment)cGroup_9.eContents().get(2);
		private final RuleCall cPermissionsPermissionsParserRuleCall_9_2_0 = (RuleCall)cPermissionsAssignment_9_2.eContents().get(0);
		private final Group cGroup_9_3 = (Group)cGroup_9.eContents().get(3);
		private final Keyword cCommaKeyword_9_3_0 = (Keyword)cGroup_9_3.eContents().get(0);
		private final Assignment cPermissionsAssignment_9_3_1 = (Assignment)cGroup_9_3.eContents().get(1);
		private final RuleCall cPermissionsPermissionsParserRuleCall_9_3_1_0 = (RuleCall)cPermissionsAssignment_9_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_9_4 = (Keyword)cGroup_9.eContents().get(4);
		private final Keyword cRightCurlyBracketKeyword_10 = (Keyword)cGroup.eContents().get(10);
		
		//Intent:
		//	{Intent} "Intent" name=EString "{" ("type" type=EString)? ("data" data=EString)? ("exceptionName"
		//	exceptionName=EString)? ("extras" "{" extras+=Bundle ("," extras+=Bundle)* "}")? ("sucessCallback"
		//	sucessCallback=Callback)? ("permissions" "{" permissions+=Permissions ("," permissions+=Permissions)* "}")? "}";
		public ParserRule getRule() { return rule; }

		//{Intent} "Intent" name=EString "{" ("type" type=EString)? ("data" data=EString)? ("exceptionName"
		//exceptionName=EString)? ("extras" "{" extras+=Bundle ("," extras+=Bundle)* "}")? ("sucessCallback"
		//sucessCallback=Callback)? ("permissions" "{" permissions+=Permissions ("," permissions+=Permissions)* "}")? "}"
		public Group getGroup() { return cGroup; }

		//{Intent}
		public Action getIntentAction_0() { return cIntentAction_0; }

		//"Intent"
		public Keyword getIntentKeyword_1() { return cIntentKeyword_1; }

		//name=EString
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }

		//EString
		public RuleCall getNameEStringParserRuleCall_2_0() { return cNameEStringParserRuleCall_2_0; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_3() { return cLeftCurlyBracketKeyword_3; }

		//("type" type=EString)?
		public Group getGroup_4() { return cGroup_4; }

		//"type"
		public Keyword getTypeKeyword_4_0() { return cTypeKeyword_4_0; }

		//type=EString
		public Assignment getTypeAssignment_4_1() { return cTypeAssignment_4_1; }

		//EString
		public RuleCall getTypeEStringParserRuleCall_4_1_0() { return cTypeEStringParserRuleCall_4_1_0; }

		//("data" data=EString)?
		public Group getGroup_5() { return cGroup_5; }

		//"data"
		public Keyword getDataKeyword_5_0() { return cDataKeyword_5_0; }

		//data=EString
		public Assignment getDataAssignment_5_1() { return cDataAssignment_5_1; }

		//EString
		public RuleCall getDataEStringParserRuleCall_5_1_0() { return cDataEStringParserRuleCall_5_1_0; }

		//("exceptionName" exceptionName=EString)?
		public Group getGroup_6() { return cGroup_6; }

		//"exceptionName"
		public Keyword getExceptionNameKeyword_6_0() { return cExceptionNameKeyword_6_0; }

		//exceptionName=EString
		public Assignment getExceptionNameAssignment_6_1() { return cExceptionNameAssignment_6_1; }

		//EString
		public RuleCall getExceptionNameEStringParserRuleCall_6_1_0() { return cExceptionNameEStringParserRuleCall_6_1_0; }

		//("extras" "{" extras+=Bundle ("," extras+=Bundle)* "}")?
		public Group getGroup_7() { return cGroup_7; }

		//"extras"
		public Keyword getExtrasKeyword_7_0() { return cExtrasKeyword_7_0; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_7_1() { return cLeftCurlyBracketKeyword_7_1; }

		//extras+=Bundle
		public Assignment getExtrasAssignment_7_2() { return cExtrasAssignment_7_2; }

		//Bundle
		public RuleCall getExtrasBundleParserRuleCall_7_2_0() { return cExtrasBundleParserRuleCall_7_2_0; }

		//("," extras+=Bundle)*
		public Group getGroup_7_3() { return cGroup_7_3; }

		//","
		public Keyword getCommaKeyword_7_3_0() { return cCommaKeyword_7_3_0; }

		//extras+=Bundle
		public Assignment getExtrasAssignment_7_3_1() { return cExtrasAssignment_7_3_1; }

		//Bundle
		public RuleCall getExtrasBundleParserRuleCall_7_3_1_0() { return cExtrasBundleParserRuleCall_7_3_1_0; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_7_4() { return cRightCurlyBracketKeyword_7_4; }

		//("sucessCallback" sucessCallback=Callback)?
		public Group getGroup_8() { return cGroup_8; }

		//"sucessCallback"
		public Keyword getSucessCallbackKeyword_8_0() { return cSucessCallbackKeyword_8_0; }

		//sucessCallback=Callback
		public Assignment getSucessCallbackAssignment_8_1() { return cSucessCallbackAssignment_8_1; }

		//Callback
		public RuleCall getSucessCallbackCallbackParserRuleCall_8_1_0() { return cSucessCallbackCallbackParserRuleCall_8_1_0; }

		//("permissions" "{" permissions+=Permissions ("," permissions+=Permissions)* "}")?
		public Group getGroup_9() { return cGroup_9; }

		//"permissions"
		public Keyword getPermissionsKeyword_9_0() { return cPermissionsKeyword_9_0; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_9_1() { return cLeftCurlyBracketKeyword_9_1; }

		//permissions+=Permissions
		public Assignment getPermissionsAssignment_9_2() { return cPermissionsAssignment_9_2; }

		//Permissions
		public RuleCall getPermissionsPermissionsParserRuleCall_9_2_0() { return cPermissionsPermissionsParserRuleCall_9_2_0; }

		//("," permissions+=Permissions)*
		public Group getGroup_9_3() { return cGroup_9_3; }

		//","
		public Keyword getCommaKeyword_9_3_0() { return cCommaKeyword_9_3_0; }

		//permissions+=Permissions
		public Assignment getPermissionsAssignment_9_3_1() { return cPermissionsAssignment_9_3_1; }

		//Permissions
		public RuleCall getPermissionsPermissionsParserRuleCall_9_3_1_0() { return cPermissionsPermissionsParserRuleCall_9_3_1_0; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_9_4() { return cRightCurlyBracketKeyword_9_4; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_10() { return cRightCurlyBracketKeyword_10; }
	}

	public class BundleElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Bundle");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cBundle_ImplParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cDoubleExtraParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		private final RuleCall cIntExtraParserRuleCall_2 = (RuleCall)cAlternatives.eContents().get(2);
		private final RuleCall cCharSequenceExtraParserRuleCall_3 = (RuleCall)cAlternatives.eContents().get(3);
		private final RuleCall cCharExtraParserRuleCall_4 = (RuleCall)cAlternatives.eContents().get(4);
		private final RuleCall cBundleExtraParserRuleCall_5 = (RuleCall)cAlternatives.eContents().get(5);
		private final RuleCall cParceableExtraParserRuleCall_6 = (RuleCall)cAlternatives.eContents().get(6);
		private final RuleCall cSerializableExtraParserRuleCall_7 = (RuleCall)cAlternatives.eContents().get(7);
		private final RuleCall cFloatExtraParserRuleCall_8 = (RuleCall)cAlternatives.eContents().get(8);
		private final RuleCall cByteExtraParserRuleCall_9 = (RuleCall)cAlternatives.eContents().get(9);
		private final RuleCall cLongExtraParserRuleCall_10 = (RuleCall)cAlternatives.eContents().get(10);
		private final RuleCall cStringExtraParserRuleCall_11 = (RuleCall)cAlternatives.eContents().get(11);
		
		//Bundle:
		//	Bundle_Impl | DoubleExtra | IntExtra | CharSequenceExtra | CharExtra | BundleExtra | ParceableExtra |
		//	SerializableExtra | FloatExtra | ByteExtra | LongExtra | StringExtra;
		public ParserRule getRule() { return rule; }

		//Bundle_Impl | DoubleExtra | IntExtra | CharSequenceExtra | CharExtra | BundleExtra | ParceableExtra | SerializableExtra
		//| FloatExtra | ByteExtra | LongExtra | StringExtra
		public Alternatives getAlternatives() { return cAlternatives; }

		//Bundle_Impl
		public RuleCall getBundle_ImplParserRuleCall_0() { return cBundle_ImplParserRuleCall_0; }

		//DoubleExtra
		public RuleCall getDoubleExtraParserRuleCall_1() { return cDoubleExtraParserRuleCall_1; }

		//IntExtra
		public RuleCall getIntExtraParserRuleCall_2() { return cIntExtraParserRuleCall_2; }

		//CharSequenceExtra
		public RuleCall getCharSequenceExtraParserRuleCall_3() { return cCharSequenceExtraParserRuleCall_3; }

		//CharExtra
		public RuleCall getCharExtraParserRuleCall_4() { return cCharExtraParserRuleCall_4; }

		//BundleExtra
		public RuleCall getBundleExtraParserRuleCall_5() { return cBundleExtraParserRuleCall_5; }

		//ParceableExtra
		public RuleCall getParceableExtraParserRuleCall_6() { return cParceableExtraParserRuleCall_6; }

		//SerializableExtra
		public RuleCall getSerializableExtraParserRuleCall_7() { return cSerializableExtraParserRuleCall_7; }

		//FloatExtra
		public RuleCall getFloatExtraParserRuleCall_8() { return cFloatExtraParserRuleCall_8; }

		//ByteExtra
		public RuleCall getByteExtraParserRuleCall_9() { return cByteExtraParserRuleCall_9; }

		//LongExtra
		public RuleCall getLongExtraParserRuleCall_10() { return cLongExtraParserRuleCall_10; }

		//StringExtra
		public RuleCall getStringExtraParserRuleCall_11() { return cStringExtraParserRuleCall_11; }
	}

	public class Bundle_ImplElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Bundle_Impl");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cBundleKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameEStringParserRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cValueKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cValueAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cValueEStringParserRuleCall_4_0 = (RuleCall)cValueAssignment_4.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_5 = (Keyword)cGroup.eContents().get(5);
		
		//Bundle_Impl returns Bundle:
		//	"Bundle" name=EString "{" "value" value=EString "}";
		public ParserRule getRule() { return rule; }

		//"Bundle" name=EString "{" "value" value=EString "}"
		public Group getGroup() { return cGroup; }

		//"Bundle"
		public Keyword getBundleKeyword_0() { return cBundleKeyword_0; }

		//name=EString
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }

		//EString
		public RuleCall getNameEStringParserRuleCall_1_0() { return cNameEStringParserRuleCall_1_0; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }

		//"value"
		public Keyword getValueKeyword_3() { return cValueKeyword_3; }

		//value=EString
		public Assignment getValueAssignment_4() { return cValueAssignment_4; }

		//EString
		public RuleCall getValueEStringParserRuleCall_4_0() { return cValueEStringParserRuleCall_4_0; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_5() { return cRightCurlyBracketKeyword_5; }
	}

	public class EStringElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "EString");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cSTRINGTerminalRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cIDTerminalRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		
		//EString returns ecore::EString:
		//	STRING | ID;
		public ParserRule getRule() { return rule; }

		//STRING | ID
		public Alternatives getAlternatives() { return cAlternatives; }

		//STRING
		public RuleCall getSTRINGTerminalRuleCall_0() { return cSTRINGTerminalRuleCall_0; }

		//ID
		public RuleCall getIDTerminalRuleCall_1() { return cIDTerminalRuleCall_1; }
	}

	public class CallbackElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Callback");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cCallbackAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cCallbackKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameEStringParserRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cDataKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cDataAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final RuleCall cDataEStringParserRuleCall_4_1_0 = (RuleCall)cDataAssignment_4_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_5 = (Keyword)cGroup.eContents().get(5);
		
		//Callback:
		//	{Callback} "Callback" name=EString "{" ("data" data=EString)? "}";
		public ParserRule getRule() { return rule; }

		//{Callback} "Callback" name=EString "{" ("data" data=EString)? "}"
		public Group getGroup() { return cGroup; }

		//{Callback}
		public Action getCallbackAction_0() { return cCallbackAction_0; }

		//"Callback"
		public Keyword getCallbackKeyword_1() { return cCallbackKeyword_1; }

		//name=EString
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }

		//EString
		public RuleCall getNameEStringParserRuleCall_2_0() { return cNameEStringParserRuleCall_2_0; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_3() { return cLeftCurlyBracketKeyword_3; }

		//("data" data=EString)?
		public Group getGroup_4() { return cGroup_4; }

		//"data"
		public Keyword getDataKeyword_4_0() { return cDataKeyword_4_0; }

		//data=EString
		public Assignment getDataAssignment_4_1() { return cDataAssignment_4_1; }

		//EString
		public RuleCall getDataEStringParserRuleCall_4_1_0() { return cDataEStringParserRuleCall_4_1_0; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_5() { return cRightCurlyBracketKeyword_5; }
	}

	public class PermissionsElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Permissions");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cPermissionsAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cPermissionsKeyword_1 = (Keyword)cGroup.eContents().get(1);
		
		//Permissions:
		//	{Permissions} "Permissions";
		public ParserRule getRule() { return rule; }

		//{Permissions} "Permissions"
		public Group getGroup() { return cGroup; }

		//{Permissions}
		public Action getPermissionsAction_0() { return cPermissionsAction_0; }

		//"Permissions"
		public Keyword getPermissionsKeyword_1() { return cPermissionsKeyword_1; }
	}

	public class ExplicitIntentElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "ExplicitIntent");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cExplicitIntentKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameEStringParserRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Keyword cTypeKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final Assignment cTypeAssignment_3_1 = (Assignment)cGroup_3.eContents().get(1);
		private final RuleCall cTypeEStringParserRuleCall_3_1_0 = (RuleCall)cTypeAssignment_3_1.eContents().get(0);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cDataKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cDataAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final RuleCall cDataEStringParserRuleCall_4_1_0 = (RuleCall)cDataAssignment_4_1.eContents().get(0);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cExceptionNameKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Assignment cExceptionNameAssignment_5_1 = (Assignment)cGroup_5.eContents().get(1);
		private final RuleCall cExceptionNameEStringParserRuleCall_5_1_0 = (RuleCall)cExceptionNameAssignment_5_1.eContents().get(0);
		private final Keyword cComponentKeyword_6 = (Keyword)cGroup.eContents().get(6);
		private final Assignment cComponentAssignment_7 = (Assignment)cGroup.eContents().get(7);
		private final RuleCall cComponentEStringParserRuleCall_7_0 = (RuleCall)cComponentAssignment_7.eContents().get(0);
		private final Group cGroup_8 = (Group)cGroup.eContents().get(8);
		private final Keyword cExtrasKeyword_8_0 = (Keyword)cGroup_8.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_8_1 = (Keyword)cGroup_8.eContents().get(1);
		private final Assignment cExtrasAssignment_8_2 = (Assignment)cGroup_8.eContents().get(2);
		private final RuleCall cExtrasBundleParserRuleCall_8_2_0 = (RuleCall)cExtrasAssignment_8_2.eContents().get(0);
		private final Group cGroup_8_3 = (Group)cGroup_8.eContents().get(3);
		private final Keyword cCommaKeyword_8_3_0 = (Keyword)cGroup_8_3.eContents().get(0);
		private final Assignment cExtrasAssignment_8_3_1 = (Assignment)cGroup_8_3.eContents().get(1);
		private final RuleCall cExtrasBundleParserRuleCall_8_3_1_0 = (RuleCall)cExtrasAssignment_8_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_8_4 = (Keyword)cGroup_8.eContents().get(4);
		private final Group cGroup_9 = (Group)cGroup.eContents().get(9);
		private final Keyword cSucessCallbackKeyword_9_0 = (Keyword)cGroup_9.eContents().get(0);
		private final Assignment cSucessCallbackAssignment_9_1 = (Assignment)cGroup_9.eContents().get(1);
		private final RuleCall cSucessCallbackCallbackParserRuleCall_9_1_0 = (RuleCall)cSucessCallbackAssignment_9_1.eContents().get(0);
		private final Group cGroup_10 = (Group)cGroup.eContents().get(10);
		private final Keyword cPermissionsKeyword_10_0 = (Keyword)cGroup_10.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_10_1 = (Keyword)cGroup_10.eContents().get(1);
		private final Assignment cPermissionsAssignment_10_2 = (Assignment)cGroup_10.eContents().get(2);
		private final RuleCall cPermissionsPermissionsParserRuleCall_10_2_0 = (RuleCall)cPermissionsAssignment_10_2.eContents().get(0);
		private final Group cGroup_10_3 = (Group)cGroup_10.eContents().get(3);
		private final Keyword cCommaKeyword_10_3_0 = (Keyword)cGroup_10_3.eContents().get(0);
		private final Assignment cPermissionsAssignment_10_3_1 = (Assignment)cGroup_10_3.eContents().get(1);
		private final RuleCall cPermissionsPermissionsParserRuleCall_10_3_1_0 = (RuleCall)cPermissionsAssignment_10_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_10_4 = (Keyword)cGroup_10.eContents().get(4);
		private final Keyword cRightCurlyBracketKeyword_11 = (Keyword)cGroup.eContents().get(11);
		
		//ExplicitIntent:
		//	"ExplicitIntent" name=EString "{" ("type" type=EString)? ("data" data=EString)? ("exceptionName"
		//	exceptionName=EString)? "component" component=EString ("extras" "{" extras+=Bundle ("," extras+=Bundle)* "}")?
		//	("sucessCallback" sucessCallback=Callback)? ("permissions" "{" permissions+=Permissions (","
		//	permissions+=Permissions)* "}")? "}";
		public ParserRule getRule() { return rule; }

		//"ExplicitIntent" name=EString "{" ("type" type=EString)? ("data" data=EString)? ("exceptionName" exceptionName=EString)?
		//"component" component=EString ("extras" "{" extras+=Bundle ("," extras+=Bundle)* "}")? ("sucessCallback"
		//sucessCallback=Callback)? ("permissions" "{" permissions+=Permissions ("," permissions+=Permissions)* "}")? "}"
		public Group getGroup() { return cGroup; }

		//"ExplicitIntent"
		public Keyword getExplicitIntentKeyword_0() { return cExplicitIntentKeyword_0; }

		//name=EString
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }

		//EString
		public RuleCall getNameEStringParserRuleCall_1_0() { return cNameEStringParserRuleCall_1_0; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }

		//("type" type=EString)?
		public Group getGroup_3() { return cGroup_3; }

		//"type"
		public Keyword getTypeKeyword_3_0() { return cTypeKeyword_3_0; }

		//type=EString
		public Assignment getTypeAssignment_3_1() { return cTypeAssignment_3_1; }

		//EString
		public RuleCall getTypeEStringParserRuleCall_3_1_0() { return cTypeEStringParserRuleCall_3_1_0; }

		//("data" data=EString)?
		public Group getGroup_4() { return cGroup_4; }

		//"data"
		public Keyword getDataKeyword_4_0() { return cDataKeyword_4_0; }

		//data=EString
		public Assignment getDataAssignment_4_1() { return cDataAssignment_4_1; }

		//EString
		public RuleCall getDataEStringParserRuleCall_4_1_0() { return cDataEStringParserRuleCall_4_1_0; }

		//("exceptionName" exceptionName=EString)?
		public Group getGroup_5() { return cGroup_5; }

		//"exceptionName"
		public Keyword getExceptionNameKeyword_5_0() { return cExceptionNameKeyword_5_0; }

		//exceptionName=EString
		public Assignment getExceptionNameAssignment_5_1() { return cExceptionNameAssignment_5_1; }

		//EString
		public RuleCall getExceptionNameEStringParserRuleCall_5_1_0() { return cExceptionNameEStringParserRuleCall_5_1_0; }

		//"component"
		public Keyword getComponentKeyword_6() { return cComponentKeyword_6; }

		//component=EString
		public Assignment getComponentAssignment_7() { return cComponentAssignment_7; }

		//EString
		public RuleCall getComponentEStringParserRuleCall_7_0() { return cComponentEStringParserRuleCall_7_0; }

		//("extras" "{" extras+=Bundle ("," extras+=Bundle)* "}")?
		public Group getGroup_8() { return cGroup_8; }

		//"extras"
		public Keyword getExtrasKeyword_8_0() { return cExtrasKeyword_8_0; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_8_1() { return cLeftCurlyBracketKeyword_8_1; }

		//extras+=Bundle
		public Assignment getExtrasAssignment_8_2() { return cExtrasAssignment_8_2; }

		//Bundle
		public RuleCall getExtrasBundleParserRuleCall_8_2_0() { return cExtrasBundleParserRuleCall_8_2_0; }

		//("," extras+=Bundle)*
		public Group getGroup_8_3() { return cGroup_8_3; }

		//","
		public Keyword getCommaKeyword_8_3_0() { return cCommaKeyword_8_3_0; }

		//extras+=Bundle
		public Assignment getExtrasAssignment_8_3_1() { return cExtrasAssignment_8_3_1; }

		//Bundle
		public RuleCall getExtrasBundleParserRuleCall_8_3_1_0() { return cExtrasBundleParserRuleCall_8_3_1_0; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_8_4() { return cRightCurlyBracketKeyword_8_4; }

		//("sucessCallback" sucessCallback=Callback)?
		public Group getGroup_9() { return cGroup_9; }

		//"sucessCallback"
		public Keyword getSucessCallbackKeyword_9_0() { return cSucessCallbackKeyword_9_0; }

		//sucessCallback=Callback
		public Assignment getSucessCallbackAssignment_9_1() { return cSucessCallbackAssignment_9_1; }

		//Callback
		public RuleCall getSucessCallbackCallbackParserRuleCall_9_1_0() { return cSucessCallbackCallbackParserRuleCall_9_1_0; }

		//("permissions" "{" permissions+=Permissions ("," permissions+=Permissions)* "}")?
		public Group getGroup_10() { return cGroup_10; }

		//"permissions"
		public Keyword getPermissionsKeyword_10_0() { return cPermissionsKeyword_10_0; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_10_1() { return cLeftCurlyBracketKeyword_10_1; }

		//permissions+=Permissions
		public Assignment getPermissionsAssignment_10_2() { return cPermissionsAssignment_10_2; }

		//Permissions
		public RuleCall getPermissionsPermissionsParserRuleCall_10_2_0() { return cPermissionsPermissionsParserRuleCall_10_2_0; }

		//("," permissions+=Permissions)*
		public Group getGroup_10_3() { return cGroup_10_3; }

		//","
		public Keyword getCommaKeyword_10_3_0() { return cCommaKeyword_10_3_0; }

		//permissions+=Permissions
		public Assignment getPermissionsAssignment_10_3_1() { return cPermissionsAssignment_10_3_1; }

		//Permissions
		public RuleCall getPermissionsPermissionsParserRuleCall_10_3_1_0() { return cPermissionsPermissionsParserRuleCall_10_3_1_0; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_10_4() { return cRightCurlyBracketKeyword_10_4; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_11() { return cRightCurlyBracketKeyword_11; }
	}

	public class ImplicitIntentElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "ImplicitIntent");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cImplicitIntentKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameEStringParserRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Keyword cTypeKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final Assignment cTypeAssignment_3_1 = (Assignment)cGroup_3.eContents().get(1);
		private final RuleCall cTypeEStringParserRuleCall_3_1_0 = (RuleCall)cTypeAssignment_3_1.eContents().get(0);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cDataKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cDataAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final RuleCall cDataEStringParserRuleCall_4_1_0 = (RuleCall)cDataAssignment_4_1.eContents().get(0);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cExceptionNameKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Assignment cExceptionNameAssignment_5_1 = (Assignment)cGroup_5.eContents().get(1);
		private final RuleCall cExceptionNameEStringParserRuleCall_5_1_0 = (RuleCall)cExceptionNameAssignment_5_1.eContents().get(0);
		private final Group cGroup_6 = (Group)cGroup.eContents().get(6);
		private final Keyword cCategoryKeyword_6_0 = (Keyword)cGroup_6.eContents().get(0);
		private final Assignment cCategoryAssignment_6_1 = (Assignment)cGroup_6.eContents().get(1);
		private final RuleCall cCategoryEStringParserRuleCall_6_1_0 = (RuleCall)cCategoryAssignment_6_1.eContents().get(0);
		private final Keyword cActionKeyword_7 = (Keyword)cGroup.eContents().get(7);
		private final Assignment cActionAssignment_8 = (Assignment)cGroup.eContents().get(8);
		private final RuleCall cActionEStringParserRuleCall_8_0 = (RuleCall)cActionAssignment_8.eContents().get(0);
		private final Group cGroup_9 = (Group)cGroup.eContents().get(9);
		private final Keyword cExtrasKeyword_9_0 = (Keyword)cGroup_9.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_9_1 = (Keyword)cGroup_9.eContents().get(1);
		private final Assignment cExtrasAssignment_9_2 = (Assignment)cGroup_9.eContents().get(2);
		private final RuleCall cExtrasBundleParserRuleCall_9_2_0 = (RuleCall)cExtrasAssignment_9_2.eContents().get(0);
		private final Group cGroup_9_3 = (Group)cGroup_9.eContents().get(3);
		private final Keyword cCommaKeyword_9_3_0 = (Keyword)cGroup_9_3.eContents().get(0);
		private final Assignment cExtrasAssignment_9_3_1 = (Assignment)cGroup_9_3.eContents().get(1);
		private final RuleCall cExtrasBundleParserRuleCall_9_3_1_0 = (RuleCall)cExtrasAssignment_9_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_9_4 = (Keyword)cGroup_9.eContents().get(4);
		private final Group cGroup_10 = (Group)cGroup.eContents().get(10);
		private final Keyword cSucessCallbackKeyword_10_0 = (Keyword)cGroup_10.eContents().get(0);
		private final Assignment cSucessCallbackAssignment_10_1 = (Assignment)cGroup_10.eContents().get(1);
		private final RuleCall cSucessCallbackCallbackParserRuleCall_10_1_0 = (RuleCall)cSucessCallbackAssignment_10_1.eContents().get(0);
		private final Group cGroup_11 = (Group)cGroup.eContents().get(11);
		private final Keyword cPermissionsKeyword_11_0 = (Keyword)cGroup_11.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_11_1 = (Keyword)cGroup_11.eContents().get(1);
		private final Assignment cPermissionsAssignment_11_2 = (Assignment)cGroup_11.eContents().get(2);
		private final RuleCall cPermissionsPermissionsParserRuleCall_11_2_0 = (RuleCall)cPermissionsAssignment_11_2.eContents().get(0);
		private final Group cGroup_11_3 = (Group)cGroup_11.eContents().get(3);
		private final Keyword cCommaKeyword_11_3_0 = (Keyword)cGroup_11_3.eContents().get(0);
		private final Assignment cPermissionsAssignment_11_3_1 = (Assignment)cGroup_11_3.eContents().get(1);
		private final RuleCall cPermissionsPermissionsParserRuleCall_11_3_1_0 = (RuleCall)cPermissionsAssignment_11_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_11_4 = (Keyword)cGroup_11.eContents().get(4);
		private final Keyword cRightCurlyBracketKeyword_12 = (Keyword)cGroup.eContents().get(12);
		
		//ImplicitIntent:
		//	"ImplicitIntent" name=EString "{" ("type" type=EString)? ("data" data=EString)? ("exceptionName"
		//	exceptionName=EString)? ("category" category=EString)? "action" action=EString ("extras" "{" extras+=Bundle (","
		//	extras+=Bundle)* "}")? ("sucessCallback" sucessCallback=Callback)? ("permissions" "{" permissions+=Permissions (","
		//	permissions+=Permissions)* "}")? "}";
		public ParserRule getRule() { return rule; }

		//"ImplicitIntent" name=EString "{" ("type" type=EString)? ("data" data=EString)? ("exceptionName" exceptionName=EString)?
		//("category" category=EString)? "action" action=EString ("extras" "{" extras+=Bundle ("," extras+=Bundle)* "}")?
		//("sucessCallback" sucessCallback=Callback)? ("permissions" "{" permissions+=Permissions ("," permissions+=Permissions)*
		//"}")? "}"
		public Group getGroup() { return cGroup; }

		//"ImplicitIntent"
		public Keyword getImplicitIntentKeyword_0() { return cImplicitIntentKeyword_0; }

		//name=EString
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }

		//EString
		public RuleCall getNameEStringParserRuleCall_1_0() { return cNameEStringParserRuleCall_1_0; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }

		//("type" type=EString)?
		public Group getGroup_3() { return cGroup_3; }

		//"type"
		public Keyword getTypeKeyword_3_0() { return cTypeKeyword_3_0; }

		//type=EString
		public Assignment getTypeAssignment_3_1() { return cTypeAssignment_3_1; }

		//EString
		public RuleCall getTypeEStringParserRuleCall_3_1_0() { return cTypeEStringParserRuleCall_3_1_0; }

		//("data" data=EString)?
		public Group getGroup_4() { return cGroup_4; }

		//"data"
		public Keyword getDataKeyword_4_0() { return cDataKeyword_4_0; }

		//data=EString
		public Assignment getDataAssignment_4_1() { return cDataAssignment_4_1; }

		//EString
		public RuleCall getDataEStringParserRuleCall_4_1_0() { return cDataEStringParserRuleCall_4_1_0; }

		//("exceptionName" exceptionName=EString)?
		public Group getGroup_5() { return cGroup_5; }

		//"exceptionName"
		public Keyword getExceptionNameKeyword_5_0() { return cExceptionNameKeyword_5_0; }

		//exceptionName=EString
		public Assignment getExceptionNameAssignment_5_1() { return cExceptionNameAssignment_5_1; }

		//EString
		public RuleCall getExceptionNameEStringParserRuleCall_5_1_0() { return cExceptionNameEStringParserRuleCall_5_1_0; }

		//("category" category=EString)?
		public Group getGroup_6() { return cGroup_6; }

		//"category"
		public Keyword getCategoryKeyword_6_0() { return cCategoryKeyword_6_0; }

		//category=EString
		public Assignment getCategoryAssignment_6_1() { return cCategoryAssignment_6_1; }

		//EString
		public RuleCall getCategoryEStringParserRuleCall_6_1_0() { return cCategoryEStringParserRuleCall_6_1_0; }

		//"action"
		public Keyword getActionKeyword_7() { return cActionKeyword_7; }

		//action=EString
		public Assignment getActionAssignment_8() { return cActionAssignment_8; }

		//EString
		public RuleCall getActionEStringParserRuleCall_8_0() { return cActionEStringParserRuleCall_8_0; }

		//("extras" "{" extras+=Bundle ("," extras+=Bundle)* "}")?
		public Group getGroup_9() { return cGroup_9; }

		//"extras"
		public Keyword getExtrasKeyword_9_0() { return cExtrasKeyword_9_0; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_9_1() { return cLeftCurlyBracketKeyword_9_1; }

		//extras+=Bundle
		public Assignment getExtrasAssignment_9_2() { return cExtrasAssignment_9_2; }

		//Bundle
		public RuleCall getExtrasBundleParserRuleCall_9_2_0() { return cExtrasBundleParserRuleCall_9_2_0; }

		//("," extras+=Bundle)*
		public Group getGroup_9_3() { return cGroup_9_3; }

		//","
		public Keyword getCommaKeyword_9_3_0() { return cCommaKeyword_9_3_0; }

		//extras+=Bundle
		public Assignment getExtrasAssignment_9_3_1() { return cExtrasAssignment_9_3_1; }

		//Bundle
		public RuleCall getExtrasBundleParserRuleCall_9_3_1_0() { return cExtrasBundleParserRuleCall_9_3_1_0; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_9_4() { return cRightCurlyBracketKeyword_9_4; }

		//("sucessCallback" sucessCallback=Callback)?
		public Group getGroup_10() { return cGroup_10; }

		//"sucessCallback"
		public Keyword getSucessCallbackKeyword_10_0() { return cSucessCallbackKeyword_10_0; }

		//sucessCallback=Callback
		public Assignment getSucessCallbackAssignment_10_1() { return cSucessCallbackAssignment_10_1; }

		//Callback
		public RuleCall getSucessCallbackCallbackParserRuleCall_10_1_0() { return cSucessCallbackCallbackParserRuleCall_10_1_0; }

		//("permissions" "{" permissions+=Permissions ("," permissions+=Permissions)* "}")?
		public Group getGroup_11() { return cGroup_11; }

		//"permissions"
		public Keyword getPermissionsKeyword_11_0() { return cPermissionsKeyword_11_0; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_11_1() { return cLeftCurlyBracketKeyword_11_1; }

		//permissions+=Permissions
		public Assignment getPermissionsAssignment_11_2() { return cPermissionsAssignment_11_2; }

		//Permissions
		public RuleCall getPermissionsPermissionsParserRuleCall_11_2_0() { return cPermissionsPermissionsParserRuleCall_11_2_0; }

		//("," permissions+=Permissions)*
		public Group getGroup_11_3() { return cGroup_11_3; }

		//","
		public Keyword getCommaKeyword_11_3_0() { return cCommaKeyword_11_3_0; }

		//permissions+=Permissions
		public Assignment getPermissionsAssignment_11_3_1() { return cPermissionsAssignment_11_3_1; }

		//Permissions
		public RuleCall getPermissionsPermissionsParserRuleCall_11_3_1_0() { return cPermissionsPermissionsParserRuleCall_11_3_1_0; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_11_4() { return cRightCurlyBracketKeyword_11_4; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_12() { return cRightCurlyBracketKeyword_12; }
	}

	public class DoubleExtraElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "DoubleExtra");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cDoubleExtraKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameEStringParserRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cValueKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cValueAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cValueEStringParserRuleCall_4_0 = (RuleCall)cValueAssignment_4.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_5 = (Keyword)cGroup.eContents().get(5);
		
		//DoubleExtra:
		//	"DoubleExtra" name=EString "{" "value" value=EString "}";
		public ParserRule getRule() { return rule; }

		//"DoubleExtra" name=EString "{" "value" value=EString "}"
		public Group getGroup() { return cGroup; }

		//"DoubleExtra"
		public Keyword getDoubleExtraKeyword_0() { return cDoubleExtraKeyword_0; }

		//name=EString
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }

		//EString
		public RuleCall getNameEStringParserRuleCall_1_0() { return cNameEStringParserRuleCall_1_0; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }

		//"value"
		public Keyword getValueKeyword_3() { return cValueKeyword_3; }

		//value=EString
		public Assignment getValueAssignment_4() { return cValueAssignment_4; }

		//EString
		public RuleCall getValueEStringParserRuleCall_4_0() { return cValueEStringParserRuleCall_4_0; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_5() { return cRightCurlyBracketKeyword_5; }
	}

	public class IntExtraElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "IntExtra");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cIntExtraKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameEStringParserRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cValueKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cValueAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cValueEStringParserRuleCall_4_0 = (RuleCall)cValueAssignment_4.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_5 = (Keyword)cGroup.eContents().get(5);
		
		//IntExtra:
		//	"IntExtra" name=EString "{" "value" value=EString "}";
		public ParserRule getRule() { return rule; }

		//"IntExtra" name=EString "{" "value" value=EString "}"
		public Group getGroup() { return cGroup; }

		//"IntExtra"
		public Keyword getIntExtraKeyword_0() { return cIntExtraKeyword_0; }

		//name=EString
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }

		//EString
		public RuleCall getNameEStringParserRuleCall_1_0() { return cNameEStringParserRuleCall_1_0; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }

		//"value"
		public Keyword getValueKeyword_3() { return cValueKeyword_3; }

		//value=EString
		public Assignment getValueAssignment_4() { return cValueAssignment_4; }

		//EString
		public RuleCall getValueEStringParserRuleCall_4_0() { return cValueEStringParserRuleCall_4_0; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_5() { return cRightCurlyBracketKeyword_5; }
	}

	public class CharSequenceExtraElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "CharSequenceExtra");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cCharSequenceExtraKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameEStringParserRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cValueKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cValueAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cValueEStringParserRuleCall_4_0 = (RuleCall)cValueAssignment_4.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_5 = (Keyword)cGroup.eContents().get(5);
		
		//CharSequenceExtra:
		//	"CharSequenceExtra" name=EString "{" "value" value=EString "}";
		public ParserRule getRule() { return rule; }

		//"CharSequenceExtra" name=EString "{" "value" value=EString "}"
		public Group getGroup() { return cGroup; }

		//"CharSequenceExtra"
		public Keyword getCharSequenceExtraKeyword_0() { return cCharSequenceExtraKeyword_0; }

		//name=EString
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }

		//EString
		public RuleCall getNameEStringParserRuleCall_1_0() { return cNameEStringParserRuleCall_1_0; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }

		//"value"
		public Keyword getValueKeyword_3() { return cValueKeyword_3; }

		//value=EString
		public Assignment getValueAssignment_4() { return cValueAssignment_4; }

		//EString
		public RuleCall getValueEStringParserRuleCall_4_0() { return cValueEStringParserRuleCall_4_0; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_5() { return cRightCurlyBracketKeyword_5; }
	}

	public class CharExtraElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "CharExtra");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cCharExtraKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameEStringParserRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cValueKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cValueAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cValueEStringParserRuleCall_4_0 = (RuleCall)cValueAssignment_4.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_5 = (Keyword)cGroup.eContents().get(5);
		
		//CharExtra:
		//	"CharExtra" name=EString "{" "value" value=EString "}";
		public ParserRule getRule() { return rule; }

		//"CharExtra" name=EString "{" "value" value=EString "}"
		public Group getGroup() { return cGroup; }

		//"CharExtra"
		public Keyword getCharExtraKeyword_0() { return cCharExtraKeyword_0; }

		//name=EString
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }

		//EString
		public RuleCall getNameEStringParserRuleCall_1_0() { return cNameEStringParserRuleCall_1_0; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }

		//"value"
		public Keyword getValueKeyword_3() { return cValueKeyword_3; }

		//value=EString
		public Assignment getValueAssignment_4() { return cValueAssignment_4; }

		//EString
		public RuleCall getValueEStringParserRuleCall_4_0() { return cValueEStringParserRuleCall_4_0; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_5() { return cRightCurlyBracketKeyword_5; }
	}

	public class BundleExtraElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "BundleExtra");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cBundleExtraKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameEStringParserRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cValueKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cValueAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cValueEStringParserRuleCall_4_0 = (RuleCall)cValueAssignment_4.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_5 = (Keyword)cGroup.eContents().get(5);
		
		//BundleExtra:
		//	"BundleExtra" name=EString "{" "value" value=EString "}";
		public ParserRule getRule() { return rule; }

		//"BundleExtra" name=EString "{" "value" value=EString "}"
		public Group getGroup() { return cGroup; }

		//"BundleExtra"
		public Keyword getBundleExtraKeyword_0() { return cBundleExtraKeyword_0; }

		//name=EString
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }

		//EString
		public RuleCall getNameEStringParserRuleCall_1_0() { return cNameEStringParserRuleCall_1_0; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }

		//"value"
		public Keyword getValueKeyword_3() { return cValueKeyword_3; }

		//value=EString
		public Assignment getValueAssignment_4() { return cValueAssignment_4; }

		//EString
		public RuleCall getValueEStringParserRuleCall_4_0() { return cValueEStringParserRuleCall_4_0; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_5() { return cRightCurlyBracketKeyword_5; }
	}

	public class ParceableExtraElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "ParceableExtra");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cParceableExtraKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameEStringParserRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cValueKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cValueAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cValueEStringParserRuleCall_4_0 = (RuleCall)cValueAssignment_4.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_5 = (Keyword)cGroup.eContents().get(5);
		
		//ParceableExtra:
		//	"ParceableExtra" name=EString "{" "value" value=EString "}";
		public ParserRule getRule() { return rule; }

		//"ParceableExtra" name=EString "{" "value" value=EString "}"
		public Group getGroup() { return cGroup; }

		//"ParceableExtra"
		public Keyword getParceableExtraKeyword_0() { return cParceableExtraKeyword_0; }

		//name=EString
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }

		//EString
		public RuleCall getNameEStringParserRuleCall_1_0() { return cNameEStringParserRuleCall_1_0; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }

		//"value"
		public Keyword getValueKeyword_3() { return cValueKeyword_3; }

		//value=EString
		public Assignment getValueAssignment_4() { return cValueAssignment_4; }

		//EString
		public RuleCall getValueEStringParserRuleCall_4_0() { return cValueEStringParserRuleCall_4_0; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_5() { return cRightCurlyBracketKeyword_5; }
	}

	public class SerializableExtraElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "SerializableExtra");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cSerializableExtraKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameEStringParserRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cValueKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cValueAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cValueEStringParserRuleCall_4_0 = (RuleCall)cValueAssignment_4.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_5 = (Keyword)cGroup.eContents().get(5);
		
		//SerializableExtra:
		//	"SerializableExtra" name=EString "{" "value" value=EString "}";
		public ParserRule getRule() { return rule; }

		//"SerializableExtra" name=EString "{" "value" value=EString "}"
		public Group getGroup() { return cGroup; }

		//"SerializableExtra"
		public Keyword getSerializableExtraKeyword_0() { return cSerializableExtraKeyword_0; }

		//name=EString
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }

		//EString
		public RuleCall getNameEStringParserRuleCall_1_0() { return cNameEStringParserRuleCall_1_0; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }

		//"value"
		public Keyword getValueKeyword_3() { return cValueKeyword_3; }

		//value=EString
		public Assignment getValueAssignment_4() { return cValueAssignment_4; }

		//EString
		public RuleCall getValueEStringParserRuleCall_4_0() { return cValueEStringParserRuleCall_4_0; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_5() { return cRightCurlyBracketKeyword_5; }
	}

	public class FloatExtraElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "FloatExtra");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cFloatExtraKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameEStringParserRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cValueKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cValueAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cValueEStringParserRuleCall_4_0 = (RuleCall)cValueAssignment_4.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_5 = (Keyword)cGroup.eContents().get(5);
		
		//FloatExtra:
		//	"FloatExtra" name=EString "{" "value" value=EString "}";
		public ParserRule getRule() { return rule; }

		//"FloatExtra" name=EString "{" "value" value=EString "}"
		public Group getGroup() { return cGroup; }

		//"FloatExtra"
		public Keyword getFloatExtraKeyword_0() { return cFloatExtraKeyword_0; }

		//name=EString
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }

		//EString
		public RuleCall getNameEStringParserRuleCall_1_0() { return cNameEStringParserRuleCall_1_0; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }

		//"value"
		public Keyword getValueKeyword_3() { return cValueKeyword_3; }

		//value=EString
		public Assignment getValueAssignment_4() { return cValueAssignment_4; }

		//EString
		public RuleCall getValueEStringParserRuleCall_4_0() { return cValueEStringParserRuleCall_4_0; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_5() { return cRightCurlyBracketKeyword_5; }
	}

	public class ByteExtraElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "ByteExtra");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cByteExtraKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameEStringParserRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cValueKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cValueAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cValueEStringParserRuleCall_4_0 = (RuleCall)cValueAssignment_4.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_5 = (Keyword)cGroup.eContents().get(5);
		
		//ByteExtra:
		//	"ByteExtra" name=EString "{" "value" value=EString "}";
		public ParserRule getRule() { return rule; }

		//"ByteExtra" name=EString "{" "value" value=EString "}"
		public Group getGroup() { return cGroup; }

		//"ByteExtra"
		public Keyword getByteExtraKeyword_0() { return cByteExtraKeyword_0; }

		//name=EString
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }

		//EString
		public RuleCall getNameEStringParserRuleCall_1_0() { return cNameEStringParserRuleCall_1_0; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }

		//"value"
		public Keyword getValueKeyword_3() { return cValueKeyword_3; }

		//value=EString
		public Assignment getValueAssignment_4() { return cValueAssignment_4; }

		//EString
		public RuleCall getValueEStringParserRuleCall_4_0() { return cValueEStringParserRuleCall_4_0; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_5() { return cRightCurlyBracketKeyword_5; }
	}

	public class LongExtraElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "LongExtra");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cLongExtraKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameEStringParserRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cValueKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cValueAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cValueEStringParserRuleCall_4_0 = (RuleCall)cValueAssignment_4.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_5 = (Keyword)cGroup.eContents().get(5);
		
		//LongExtra:
		//	"LongExtra" name=EString "{" "value" value=EString "}";
		public ParserRule getRule() { return rule; }

		//"LongExtra" name=EString "{" "value" value=EString "}"
		public Group getGroup() { return cGroup; }

		//"LongExtra"
		public Keyword getLongExtraKeyword_0() { return cLongExtraKeyword_0; }

		//name=EString
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }

		//EString
		public RuleCall getNameEStringParserRuleCall_1_0() { return cNameEStringParserRuleCall_1_0; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }

		//"value"
		public Keyword getValueKeyword_3() { return cValueKeyword_3; }

		//value=EString
		public Assignment getValueAssignment_4() { return cValueAssignment_4; }

		//EString
		public RuleCall getValueEStringParserRuleCall_4_0() { return cValueEStringParserRuleCall_4_0; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_5() { return cRightCurlyBracketKeyword_5; }
	}

	public class StringExtraElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "StringExtra");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cStringExtraKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameEStringParserRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cValueKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cValueAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cValueEStringParserRuleCall_4_0 = (RuleCall)cValueAssignment_4.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_5 = (Keyword)cGroup.eContents().get(5);
		
		//StringExtra:
		//	"StringExtra" name=EString "{" "value" value=EString "}";
		public ParserRule getRule() { return rule; }

		//"StringExtra" name=EString "{" "value" value=EString "}"
		public Group getGroup() { return cGroup; }

		//"StringExtra"
		public Keyword getStringExtraKeyword_0() { return cStringExtraKeyword_0; }

		//name=EString
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }

		//EString
		public RuleCall getNameEStringParserRuleCall_1_0() { return cNameEStringParserRuleCall_1_0; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }

		//"value"
		public Keyword getValueKeyword_3() { return cValueKeyword_3; }

		//value=EString
		public Assignment getValueAssignment_4() { return cValueAssignment_4; }

		//EString
		public RuleCall getValueEStringParserRuleCall_4_0() { return cValueEStringParserRuleCall_4_0; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_5() { return cRightCurlyBracketKeyword_5; }
	}
	
	
	private IntentElements pIntent;
	private BundleElements pBundle;
	private Bundle_ImplElements pBundle_Impl;
	private EStringElements pEString;
	private CallbackElements pCallback;
	private PermissionsElements pPermissions;
	private ExplicitIntentElements pExplicitIntent;
	private ImplicitIntentElements pImplicitIntent;
	private DoubleExtraElements pDoubleExtra;
	private IntExtraElements pIntExtra;
	private CharSequenceExtraElements pCharSequenceExtra;
	private CharExtraElements pCharExtra;
	private BundleExtraElements pBundleExtra;
	private ParceableExtraElements pParceableExtra;
	private SerializableExtraElements pSerializableExtra;
	private FloatExtraElements pFloatExtra;
	private ByteExtraElements pByteExtra;
	private LongExtraElements pLongExtra;
	private StringExtraElements pStringExtra;
	
	private final Grammar grammar;

	private TerminalsGrammarAccess gaTerminals;

	@Inject
	public IntentDslGrammarAccess(GrammarProvider grammarProvider,
		TerminalsGrammarAccess gaTerminals) {
		this.grammar = internalFindGrammar(grammarProvider);
		this.gaTerminals = gaTerminals;
	}
	
	protected Grammar internalFindGrammar(GrammarProvider grammarProvider) {
		Grammar grammar = grammarProvider.getGrammar(this);
		while (grammar != null) {
			if ("itu.dk.aamj.intentdsl.IntentDsl".equals(grammar.getName())) {
				return grammar;
			}
			List<Grammar> grammars = grammar.getUsedGrammars();
			if (!grammars.isEmpty()) {
				grammar = grammars.iterator().next();
			} else {
				return null;
			}
		}
		return grammar;
	}
	
	
	public Grammar getGrammar() {
		return grammar;
	}
	

	public TerminalsGrammarAccess getTerminalsGrammarAccess() {
		return gaTerminals;
	}

	
	//Intent:
	//	{Intent} "Intent" name=EString "{" ("type" type=EString)? ("data" data=EString)? ("exceptionName"
	//	exceptionName=EString)? ("extras" "{" extras+=Bundle ("," extras+=Bundle)* "}")? ("sucessCallback"
	//	sucessCallback=Callback)? ("permissions" "{" permissions+=Permissions ("," permissions+=Permissions)* "}")? "}";
	public IntentElements getIntentAccess() {
		return (pIntent != null) ? pIntent : (pIntent = new IntentElements());
	}
	
	public ParserRule getIntentRule() {
		return getIntentAccess().getRule();
	}

	//Bundle:
	//	Bundle_Impl | DoubleExtra | IntExtra | CharSequenceExtra | CharExtra | BundleExtra | ParceableExtra |
	//	SerializableExtra | FloatExtra | ByteExtra | LongExtra | StringExtra;
	public BundleElements getBundleAccess() {
		return (pBundle != null) ? pBundle : (pBundle = new BundleElements());
	}
	
	public ParserRule getBundleRule() {
		return getBundleAccess().getRule();
	}

	//Bundle_Impl returns Bundle:
	//	"Bundle" name=EString "{" "value" value=EString "}";
	public Bundle_ImplElements getBundle_ImplAccess() {
		return (pBundle_Impl != null) ? pBundle_Impl : (pBundle_Impl = new Bundle_ImplElements());
	}
	
	public ParserRule getBundle_ImplRule() {
		return getBundle_ImplAccess().getRule();
	}

	//EString returns ecore::EString:
	//	STRING | ID;
	public EStringElements getEStringAccess() {
		return (pEString != null) ? pEString : (pEString = new EStringElements());
	}
	
	public ParserRule getEStringRule() {
		return getEStringAccess().getRule();
	}

	//Callback:
	//	{Callback} "Callback" name=EString "{" ("data" data=EString)? "}";
	public CallbackElements getCallbackAccess() {
		return (pCallback != null) ? pCallback : (pCallback = new CallbackElements());
	}
	
	public ParserRule getCallbackRule() {
		return getCallbackAccess().getRule();
	}

	//Permissions:
	//	{Permissions} "Permissions";
	public PermissionsElements getPermissionsAccess() {
		return (pPermissions != null) ? pPermissions : (pPermissions = new PermissionsElements());
	}
	
	public ParserRule getPermissionsRule() {
		return getPermissionsAccess().getRule();
	}

	//ExplicitIntent:
	//	"ExplicitIntent" name=EString "{" ("type" type=EString)? ("data" data=EString)? ("exceptionName"
	//	exceptionName=EString)? "component" component=EString ("extras" "{" extras+=Bundle ("," extras+=Bundle)* "}")?
	//	("sucessCallback" sucessCallback=Callback)? ("permissions" "{" permissions+=Permissions (","
	//	permissions+=Permissions)* "}")? "}";
	public ExplicitIntentElements getExplicitIntentAccess() {
		return (pExplicitIntent != null) ? pExplicitIntent : (pExplicitIntent = new ExplicitIntentElements());
	}
	
	public ParserRule getExplicitIntentRule() {
		return getExplicitIntentAccess().getRule();
	}

	//ImplicitIntent:
	//	"ImplicitIntent" name=EString "{" ("type" type=EString)? ("data" data=EString)? ("exceptionName"
	//	exceptionName=EString)? ("category" category=EString)? "action" action=EString ("extras" "{" extras+=Bundle (","
	//	extras+=Bundle)* "}")? ("sucessCallback" sucessCallback=Callback)? ("permissions" "{" permissions+=Permissions (","
	//	permissions+=Permissions)* "}")? "}";
	public ImplicitIntentElements getImplicitIntentAccess() {
		return (pImplicitIntent != null) ? pImplicitIntent : (pImplicitIntent = new ImplicitIntentElements());
	}
	
	public ParserRule getImplicitIntentRule() {
		return getImplicitIntentAccess().getRule();
	}

	//DoubleExtra:
	//	"DoubleExtra" name=EString "{" "value" value=EString "}";
	public DoubleExtraElements getDoubleExtraAccess() {
		return (pDoubleExtra != null) ? pDoubleExtra : (pDoubleExtra = new DoubleExtraElements());
	}
	
	public ParserRule getDoubleExtraRule() {
		return getDoubleExtraAccess().getRule();
	}

	//IntExtra:
	//	"IntExtra" name=EString "{" "value" value=EString "}";
	public IntExtraElements getIntExtraAccess() {
		return (pIntExtra != null) ? pIntExtra : (pIntExtra = new IntExtraElements());
	}
	
	public ParserRule getIntExtraRule() {
		return getIntExtraAccess().getRule();
	}

	//CharSequenceExtra:
	//	"CharSequenceExtra" name=EString "{" "value" value=EString "}";
	public CharSequenceExtraElements getCharSequenceExtraAccess() {
		return (pCharSequenceExtra != null) ? pCharSequenceExtra : (pCharSequenceExtra = new CharSequenceExtraElements());
	}
	
	public ParserRule getCharSequenceExtraRule() {
		return getCharSequenceExtraAccess().getRule();
	}

	//CharExtra:
	//	"CharExtra" name=EString "{" "value" value=EString "}";
	public CharExtraElements getCharExtraAccess() {
		return (pCharExtra != null) ? pCharExtra : (pCharExtra = new CharExtraElements());
	}
	
	public ParserRule getCharExtraRule() {
		return getCharExtraAccess().getRule();
	}

	//BundleExtra:
	//	"BundleExtra" name=EString "{" "value" value=EString "}";
	public BundleExtraElements getBundleExtraAccess() {
		return (pBundleExtra != null) ? pBundleExtra : (pBundleExtra = new BundleExtraElements());
	}
	
	public ParserRule getBundleExtraRule() {
		return getBundleExtraAccess().getRule();
	}

	//ParceableExtra:
	//	"ParceableExtra" name=EString "{" "value" value=EString "}";
	public ParceableExtraElements getParceableExtraAccess() {
		return (pParceableExtra != null) ? pParceableExtra : (pParceableExtra = new ParceableExtraElements());
	}
	
	public ParserRule getParceableExtraRule() {
		return getParceableExtraAccess().getRule();
	}

	//SerializableExtra:
	//	"SerializableExtra" name=EString "{" "value" value=EString "}";
	public SerializableExtraElements getSerializableExtraAccess() {
		return (pSerializableExtra != null) ? pSerializableExtra : (pSerializableExtra = new SerializableExtraElements());
	}
	
	public ParserRule getSerializableExtraRule() {
		return getSerializableExtraAccess().getRule();
	}

	//FloatExtra:
	//	"FloatExtra" name=EString "{" "value" value=EString "}";
	public FloatExtraElements getFloatExtraAccess() {
		return (pFloatExtra != null) ? pFloatExtra : (pFloatExtra = new FloatExtraElements());
	}
	
	public ParserRule getFloatExtraRule() {
		return getFloatExtraAccess().getRule();
	}

	//ByteExtra:
	//	"ByteExtra" name=EString "{" "value" value=EString "}";
	public ByteExtraElements getByteExtraAccess() {
		return (pByteExtra != null) ? pByteExtra : (pByteExtra = new ByteExtraElements());
	}
	
	public ParserRule getByteExtraRule() {
		return getByteExtraAccess().getRule();
	}

	//LongExtra:
	//	"LongExtra" name=EString "{" "value" value=EString "}";
	public LongExtraElements getLongExtraAccess() {
		return (pLongExtra != null) ? pLongExtra : (pLongExtra = new LongExtraElements());
	}
	
	public ParserRule getLongExtraRule() {
		return getLongExtraAccess().getRule();
	}

	//StringExtra:
	//	"StringExtra" name=EString "{" "value" value=EString "}";
	public StringExtraElements getStringExtraAccess() {
		return (pStringExtra != null) ? pStringExtra : (pStringExtra = new StringExtraElements());
	}
	
	public ParserRule getStringExtraRule() {
		return getStringExtraAccess().getRule();
	}

	//terminal ID:
	//	"^"? ("a".."z" | "A".."Z" | "_") ("a".."z" | "A".."Z" | "_" | "0".."9")*;
	public TerminalRule getIDRule() {
		return gaTerminals.getIDRule();
	} 

	//terminal INT returns ecore::EInt:
	//	"0".."9"+;
	public TerminalRule getINTRule() {
		return gaTerminals.getINTRule();
	} 

	//terminal STRING:
	//	"\"" ("\\" ("b" | "t" | "n" | "f" | "r" | "u" | "\"" | "\'" | "\\") | !("\\" | "\""))* "\"" | "\'" ("\\" ("b" | "t" |
	//	"n" | "f" | "r" | "u" | "\"" | "\'" | "\\") | !("\\" | "\'"))* "\'";
	public TerminalRule getSTRINGRule() {
		return gaTerminals.getSTRINGRule();
	} 

	//terminal ML_COMMENT:
	//	"/ *"->"* /";
	public TerminalRule getML_COMMENTRule() {
		return gaTerminals.getML_COMMENTRule();
	} 

	//terminal SL_COMMENT:
	//	"//" !("\n" | "\r")* ("\r"? "\n")?;
	public TerminalRule getSL_COMMENTRule() {
		return gaTerminals.getSL_COMMENTRule();
	} 

	//terminal WS:
	//	(" " | "\t" | "\r" | "\n")+;
	public TerminalRule getWSRule() {
		return gaTerminals.getWSRule();
	} 

	//terminal ANY_OTHER:
	//	.;
	public TerminalRule getANY_OTHERRule() {
		return gaTerminals.getANY_OTHERRule();
	} 
}
