/*
 * generated by Xtext
 */
package itu.dk.aamj.intentdsl.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class IntentDslUiModule extends itu.dk.aamj.intentdsl.ui.AbstractIntentDslUiModule {
	public IntentDslUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
