/*
 * generated by Xtext
 */
package itu.dk.aamj.intentdsl.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import itu.dk.aamj.intentdsl.ui.internal.IntentDslActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class IntentDslExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return IntentDslActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return IntentDslActivator.getInstance().getInjector(IntentDslActivator.ITU_DK_AAMJ_INTENTDSL_INTENTDSL);
	}
	
}
