/*
* generated by Xtext
*/
package itu.dk.aamj.intentdsl.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class IntentDslAntlrTokenFileProvider implements IAntlrTokenFileProvider {
	
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
    	return classLoader.getResourceAsStream("itu/dk/aamj/intentdsl/parser/antlr/internal/InternalIntentDsl.tokens");
	}
}
