/*
* generated by Xtext
*/
package itu.dk.aamj.intentdsl.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import itu.dk.aamj.intentdsl.services.IntentDslGrammarAccess;

public class IntentDslParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private IntentDslGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected itu.dk.aamj.intentdsl.parser.antlr.internal.InternalIntentDslParser createParser(XtextTokenStream stream) {
		return new itu.dk.aamj.intentdsl.parser.antlr.internal.InternalIntentDslParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "Intent";
	}
	
	public IntentDslGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(IntentDslGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
