/*
 * generated by Xtext
 */
package itu.dk.aamj.intentdsl;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class IntentDslRuntimeModule extends itu.dk.aamj.intentdsl.AbstractIntentDslRuntimeModule {

}
