<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="intent" nsURI="itu.dk.aamj" nsPrefix="intent">
  <eClassifiers xsi:type="ecore:EClass" name="Intent" abstract="true" eSuperTypes="#//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="extras" upperBound="-1"
        eType="#//Bundle" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="data" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="sucessCallback" eType="#//Callback"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="exceptionName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="permissions" upperBound="-1"
        eType="#//Permissions" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Bundle" abstract="true" eSuperTypes="#//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ExplicitIntent" eSuperTypes="#//Intent">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="component" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ImplicitIntent" eSuperTypes="#//Intent">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="category" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="action" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DoubleExtra" eSuperTypes="#//Bundle"/>
  <eClassifiers xsi:type="ecore:EClass" name="IntExtra" eSuperTypes="#//Bundle"/>
  <eClassifiers xsi:type="ecore:EClass" name="CharSequenceExtra" eSuperTypes="#//Bundle"/>
  <eClassifiers xsi:type="ecore:EClass" name="CharExtra" eSuperTypes="#//Bundle"/>
  <eClassifiers xsi:type="ecore:EClass" name="BundleExtra" eSuperTypes="#//Bundle"/>
  <eClassifiers xsi:type="ecore:EClass" name="ParceableExtra" eSuperTypes="#//Bundle"/>
  <eClassifiers xsi:type="ecore:EClass" name="SerializableExtra" eSuperTypes="#//Bundle"/>
  <eClassifiers xsi:type="ecore:EClass" name="FloatExtra" eSuperTypes="#//Bundle"/>
  <eClassifiers xsi:type="ecore:EClass" name="ByteExtra" eSuperTypes="#//Bundle"/>
  <eClassifiers xsi:type="ecore:EClass" name="LongExtra" eSuperTypes="#//Bundle"/>
  <eClassifiers xsi:type="ecore:EClass" name="StringExtra" eSuperTypes="#//Bundle"/>
  <eClassifiers xsi:type="ecore:EClass" name="Callback" eSuperTypes="#//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="data" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Permissions" eSuperTypes="#//NamedElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="NamedElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Model" eSuperTypes="#//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="intents" upperBound="-1"
        eType="#//Intent" containment="true"/>
  </eClassifiers>
</ecore:EPackage>
