/*
* generated by Xtext
*/
package itu.dk.aamj.intentdsl.ui.contentassist;

import itu.dk.aamj.intentdsl.ui.contentassist.AbstractIntentDslProposalProvider;
/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class IntentDslProposalProvider extends AbstractIntentDslProposalProvider {

}
